version: "3"

services:
  db:
    container_name: db
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: penta-app
      MYSQL_PASSWORD: 12345678
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

  api:
    container_name: api
    image: api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env 
    ports:
      - 3000:3000
    depends_on:
      - db
        # condition: service_healthy
            # condition: service_healthy

volumes:
  db_data:
